var music = [
  ["Tera Ghata","0KNk-Joi-NM"],
  ["Na Hona Tumse Door","dyu3LmA4yJY"],
  ["Mein Ishq Tera Ban Jaau","F5gJp4iSMQs"],
  ["Itna Chahu Tumhe","kaW7jEKw1b0"],
  ["Bekarar Dil Mera","HPnvMKvrijA"],
  ["Chehra Ye Chand Sa","Z9RFTUUyPfo"],
  ["Terre Pyaar Mein","ia5CdcuqSWk"],
  ["Pehli Dafa","L9sc0ef1awM"],
  ["Subah Se Shaam","apzKh8oxqoQ"],
  ["Dua Karo","j8mfNs1oe2w"],
  ["Aankhein Band Karke","hfpZCQvHn0c"],
  ["Aise Na Mujhe Tum Dekho","TXLh8210NbM"],
  ["Saaton Janam","AoM3AC6iVLQ"],
  ["Dard Tere","ap_P-xO7OI8"],
  ["Chand Naraz Hai","NiC-M1BHFoo"],
  ["Dil Na Todunga","0HX_19_zkio"],
  ["Holi Mein Rangeele","XBqzieMSz-Y"],
  ["Tera Rahoon","i_G1Sl2PVqE"],
  ["Dil Toota Hi Raha","BTRtfW-CjXU"],
  ["Neend Churai Meri","qCYby9dc480"],
  ["Ijazat","Q4PPAU6F4Cc"],
  ["Piya Re Piya","FcFbQmJv7fU"],
  ["Sunn Zara","ZIvNNe2FwHo"],
  ["Tu Mera Sanam","PuCQPmNo-aY"]
]
